import '../styles/main.css';

function TermsOfService() {
  return (
    <div className="container legal-page">
      <div className="page-header">
        <h1>Terms of Service</h1>
        <p className="subtitle">Last Updated: January 21, 2026</p>
      </div>

      <div className="legal-content">
        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using GhostWriter ("Service"), you accept and agree to be bound by the terms and provisions of this agreement.
            If you do not agree to these terms, please do not use this Service.
          </p>
        </section>

        <section>
          <h2>2. Service Description</h2>
          <p>
            GhostWriter is an AI-powered story generation platform that creates fiction and biography content based on user inputs.
            The Service uses artificial intelligence and machine learning models to generate creative content.
          </p>
        </section>

        <section>
          <h2>3. User-Generated Content & Ownership</h2>
          <h3>3.1 Your Content Ownership</h3>
          <p>
            You retain all intellectual property rights to the stories you generate using GhostWriter. 
            The content generated belongs to you, the user who created it, subject to the limitations below.
          </p>
          <h3>3.2 AI-Generated Content Disclaimer</h3>
          <p>
            Content is generated by AI and may contain errors, inaccuracies, or unintended similarities to existing works.
            You are solely responsible for reviewing, editing, and verifying all generated content before publication or use.
          </p>
          <h3>3.3 Prohibited Content</h3>
          <p>
            You agree not to generate content that:
          </p>
          <ul>
            <li>Violates any law or regulation</li>
            <li>Infringes on intellectual property rights of others</li>
            <li>Contains hate speech, harassment, or threats</li>
            <li>Promotes illegal activities</li>
            <li>Contains explicit content involving minors</li>
          </ul>
        </section>

        <section>
          <h2>4. Credit System & Payments</h2>
          <h3>4.1 Credit Purchase</h3>
          <p>
            Credits are purchased through our payment processor (Stripe). All sales are final and non-refundable except as required by law.
          </p>
          <h3>4.2 Credit Usage</h3>
          <p>
            Credits are consumed upon story generation. Credit costs vary by story length and type.
            Unused credits do not expire but may be forfeited if account terms are violated.
          </p>
          <h3>4.3 Refund Policy</h3>
          <p>
            Refunds are only provided in cases of technical failure where content generation fails and credits are not automatically restored.
            Dissatisfaction with AI-generated content quality is not grounds for refund.
          </p>
        </section>

        <section>
          <h2>5. Service Availability & Limitations</h2>
          <h3>5.1 No Guarantees</h3>
          <p>
            THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.
            We do not guarantee uninterrupted service, error-free operation, or that generated content will meet your expectations.
          </p>
          <h3>5.2 Service Modifications</h3>
          <p>
            We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
          </p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW:
          </p>
          <ul>
            <li>We are not liable for any indirect, incidental, special, or consequential damages</li>
            <li>Our total liability shall not exceed the amount you paid for credits in the past 12 months</li>
            <li>We are not responsible for copyright infringement claims arising from AI-generated content</li>
            <li>We are not liable for any damages resulting from unauthorized access to your account</li>
          </ul>
        </section>

        <section>
          <h2>7. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless GhostWriter, its owners, operators, and affiliates from any claims, damages, losses, or expenses
            arising from:
          </p>
          <ul>
            <li>Your use of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your publication or distribution of AI-generated content</li>
            <li>Copyright infringement claims related to generated content</li>
          </ul>
        </section>

        <section>
          <h2>8. Copyright & AI Training</h2>
          <h3>8.1 Your Content for AI Training</h3>
          <p>
            We DO NOT use your generated stories to train our AI models. Your content remains private and is not shared with third parties.
          </p>
          <h3>8.2 Third-Party AI Models</h3>
          <p>
            We use third-party AI providers (such as OpenAI, Anthropic, Meta). Their terms of service also apply to content generation.
          </p>
        </section>

        <section>
          <h2>9. Account Termination</h2>
          <p>
            We reserve the right to suspend or terminate accounts that:
          </p>
          <ul>
            <li>Violate these Terms of Service</li>
            <li>Engage in fraudulent payment activity</li>
            <li>Abuse the Service or attempt to circumvent credit costs</li>
            <li>Generate prohibited content</li>
          </ul>
          <p>
            Upon termination, unused credits are forfeited without refund.
          </p>
        </section>

        <section>
          <h2>10. Privacy & Data</h2>
          <p>
            Your use of the Service is also governed by our Privacy Policy. We collect and store:
          </p>
          <ul>
            <li>Account information (email, name)</li>
            <li>Generated story content</li>
            <li>Payment information (processed securely by Stripe)</li>
            <li>Usage analytics</li>
          </ul>
          <p>
            We do not sell your personal data. Stories are stored for your access but may be deleted after account termination.
          </p>
        </section>

        <section>
          <h2>11. Dispute Resolution</h2>
          <h3>11.1 Governing Law</h3>
          <p>
            These Terms are governed by the laws of the State of Mississippi, United States, without regard to conflict of law principles.
          </p>
          <h3>11.2 Arbitration</h3>
          <p>
            Any disputes shall be resolved through binding arbitration in accordance with the American Arbitration Association rules.
            You waive your right to participate in class action lawsuits.
          </p>
        </section>

        <section>
          <h2>12. Changes to Terms</h2>
          <p>
            We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of new Terms.
            Material changes will be notified via email.
          </p>
        </section>

        <section>
          <h2>13. Contact Information</h2>
          <p>
            For questions about these Terms, contact us at:
          </p>
          <p className="contact-info">
            Email: <a href="mailto:support@ghostwriter.app">support@ghostwriter.app</a><br />
            Business Entity: GhostWriter LLC (if applicable)<br />
            Location: Madison, Mississippi, USA
          </p>
        </section>

        <section>
          <h2>14. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full effect.
          </p>
        </section>

        <div className="legal-footer">
          <p><strong>BY USING GHOSTWRITER, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS.</strong></p>
        </div>
      </div>
    </div>
  );
}

export default TermsOfService;
