import { Link } from 'react-router-dom';
import './Footer.css';

function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="footer">
      <div className="footer-container">
        <div className="footer-section">
          <h3 className="footer-logo">👻 GhostWriter</h3>
          <p className="footer-tagline">AI-powered story generation with a deadpan twist</p>
        </div>

        <div className="footer-section">
          <h4>Product</h4>
          <ul className="footer-links">
            <li><Link to="/">Home</Link></li>
            <li><Link to="/dashboard">Dashboard</Link></li>
            <li><Link to="/credits">Buy Credits</Link></li>
            <li><Link to="/transactions">Transactions</Link></li>
          </ul>
        </div>

        <div className="footer-section">
          <h4>Legal</h4>
          <ul className="footer-links">
            <li><Link to="/terms">Terms of Service</Link></li>
            <li><a href="mailto:support@ghostwriter.app">Contact Support</a></li>
          </ul>
        </div>

        <div className="footer-section">
          <h4>About</h4>
          <p className="footer-text">
            Built with Llama 3.3 70B. Stories generated by AI, owned by you.
            Review all content before publication.
          </p>
        </div>
      </div>

      <div className="footer-bottom">
        <p>© {currentYear} GhostWriter. All rights reserved. | Madison, MS</p>
        <p className="footer-disclaimer">
          AI-generated content provided "AS IS" without warranty. Users assume all copyright risks.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
